### ISSUE TITLE
Issue with Really Simple SSL

### ISSUE THREAD

**Issue by leezhiwei** [Really-Simple-Plugins/really-simple-ssl#556] opened 2022-11-17 14:51 UTC
On my site, the settings panel is super glitched out, please help. Thank you.
![image](https://user-images.githubusercontent.com/13075070/202478615-5bea7948-b273-4d9d-bcd1-26399eaaefd4.png)

**Comment by rlankhorst** [comment] 2022-11-17 16:14
@leezhiwei on some sites the X-HTTP-NONCE is not sent. Another logged in check is now used in the current main of this github, you can update your current version with this one. 

It will be released next tuesday. 

Let me know if you have any questions.

**Comment by leezhiwei** [comment] 2022-11-17 16:18
Right. How should I go from this? I'm on the latest version.

**Comment by rlankhorst** [comment] 2022-11-17 16:27
I've uploaded the latest version in a zip file here:
https://really-simple-ssl.com/really-simple-ssl.zip

You can download it, then go to plugins, add new, upload. Then WordPress will ask if you want to replace. You can choose 'yes'.

**Comment by leezhiwei** [comment] 2022-11-17 16:36
Alright

**Comment by rlankhorst** [comment] 2022-11-17 17:10
When on the settings page, (using Chrome) can you right click on the screen, then click "inspect", "console"?
Then you should see some errors on the bottom of your screen. If you can post that image here, That might tell me something.

**Comment by leezhiwei** [comment] 2022-11-17 17:14
![image](https://user-images.githubusercontent.com/13075070/202512664-16c81868-def8-42da-ab95-c3e363a44394.png)
Here's my console.

**Comment by rlankhorst** [comment] 2022-11-17 17:23
When I try your domain, with behind it: 
/wp-json/wp/v2/posts

I also get a not found. 
You can compare with our site: putting this in the browser https://really-simple-ssl.com/wp-json/wp/v2/posts
results in posts. 

On your site it doesn't exist. The two most likely causes are: permalinks need to be flushed, or another plugin blocking the rest api. 

- First, can you try re-saving the permalinks in the general WordPress settings, settings/permalinks?
- If that doesn't help, can you check if you have a plugin or tool active which blocks the rest api?

**Comment by leezhiwei** [comment] 2022-11-17 17:27
I had an issue with posting about invalid json response. I think somehow my permalinks are screwed up. How do I resolve it?

**Comment by leezhiwei** [comment] 2022-11-17 17:28
I'm self hosted so I have full access to the file system. I am running apache2.

**Comment by rlankhorst** [comment] 2022-11-17 17:32
Usually, to resolve permalinks issues, you can go to settings/permalinks, then click save. This will flush the permalinks.

**Comment by leezhiwei** [comment] 2022-11-17 17:37
Problem is not resolved. I have these plugins
Advanced Post Block, Cloudflare, Jetpack, pdf embedder, Really Simple SSL, Spectra, Starter Templates, WP Mail SMTP, WPForms Lite, Yoast Seo (deactivated).

**Comment by rlankhorst** [comment] 2022-11-17 17:42
Your permalinks seem not to work at all. For example the /about url is not loading. Can you rename your .htaccess file to .htaccess-bkp, then re-save the permalinks? This should re-generate the .htaccess file, and resolve the issue.

**Comment by leezhiwei** [comment] 2022-11-17 17:45
Just did. Still seems the same though.

**Comment by rlankhorst** [comment] 2022-11-17 17:47
Can you post your .htaccess contents? or mail it to rogier(at)really-simple-plugins.com. I'd like to check that file. It looks as if there's something wrong with it.

**Comment by leezhiwei** [comment] 2022-11-17 17:51
Just sent it over.

**Comment by rlankhorst** [comment] 2022-11-17 18:03
That looks fine. I googled a bit, and found this thread:
https://stackoverflow.com/questions/13149418/the-requested-url-about-was-not-found-on-this-server

Maybe the suggestion about this will help (see the instructions in the article):
Change the AllowOverride None to AllowOverride All.

Otherwise, I'd ask your hosting company to check what the problem is with the permalinks. It doesn't seem to be a wordpress problem, but an apache configuration problem.

**Comment by leezhiwei** [comment] 2022-11-17 18:13
Fixed it. Needed to enable mod_rewrite

**Comment by rlankhorst** [comment] 2022-11-17 18:16
Great!

**Comment by leezhiwei** [comment] 2022-11-17 18:16
Thanks for all the help!

**Closed by rlankhorst** 2022-11-17 18:16 UTC
