### ISSUE TITLE
Settings screen shows only three blank white areas

### ISSUE THREAD

**Issue by kps1ny** [Really-Simple-Plugins/really-simple-ssl#594] opened 2023-01-27 15:10 UTC
Following what seemed to be a clean plug-in installation, the settings screen is effectively blank. Logging out and back in as admin, and deactivating and reactivating the plug-in, had no effect.

Please update the plug-in to check for whatever condition is causing this and show advice on how to resolve it instead of blank areas.

<img width="1373" alt="Screenshot 2023-01-27 at 9 45 35 AM" src="https://user-images.githubusercontent.com/855599/215119530-0f60371b-4604-43aa-ac33-2929cbdee66a.png">

**Comment by rlankhorst** [comment] 2023-01-27 16:03
@kps1ny thanks for your input.  I'm looking into ways to identify such issues. Can you check in your console (right click, inspect element, console) what errors you see there? That will tell me more about your specific issue.

**Comment by kps1ny** [comment] 2023-01-27 16:09
Sure. Should have looked at that earlier... it goes into an unending loop as shown in the uploaded image.

Something related to a 403 error.

![Screenshot 2023-01-27 at 11 06 02 AM](https://user-images.githubusercontent.com/855599/215133483-5bf52e48-6bd5-480f-a212-abb679ceb6fc.png)

Note that I don't have much system access here, so I will have to act as an intermediary with someone else, who may then also have to ask a sysadmin to check things, if it comes to needing further information about .htaccess files and server configurations, etc.

@rlankhorst

**Comment by kps1ny** [comment] 2023-01-27 16:10
Also, I have tried deactivating all of our other plug-ins, then reloading the settings page for this one, with no change to seeing only the 3 blank white areas.

**Comment by rlankhorst** [comment] 2023-01-27 16:12
@kps1ny It looks like something is blocking the rest api. This is often caused by either the hosting company, or a security plugin which blocks the rest api. 

I think it should be possible to check for the response code, we can then show the user that there is either a 403 or 404 response, which might help the user find the cause. But it's not really possible for us to detect what is causing those response codes.

**Comment by kps1ny** [comment] 2023-01-27 16:15
@rlankhorst   OK, I will pass that along and see what they can make of it. Thanks for checking on this. I'll update as relevant.

**Comment by rlankhorst** [comment] 2023-03-23 20:16
The latest version includes several fallback mechanisms which seems to resolve most situations that still had this problem. Closing this as resolved.

**Closed** 2023-03-23 20:16 UTC
